<a href="https://colab.research.google.com/github/datagrad/Learning-Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

* Python NumPy is a general-purpose array processing package which provides tools for handling the n-dimensional arrays.
* It provides various computing tools such as comprehensive mathematical functions, linear algebra routines. 
* NumPy provides both the flexibility of Python and the speed of well-optimized compiled C code.
* It’s easy to use syntax makes it highly accessible and productive for programmers from any background.



In [10]:
import numpy as np


### Object Type

In [11]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Type of object
print("Array is of type: ", type(arr))


Array is of type:  <class 'numpy.ndarray'>


In [48]:
array1 = np.array([["a", "b","c"],[1,2,3],["t",2,"p"]])

print(array1)

print(""*10)
print("Shape: ",array1.shape)

print(""*10)
print("Shape: ",array1.ndim)

print(""*10)
print("Shape: ",array1.size)

print(""*10)
print("Shape: ",array1.dtype)

[['a' 'b' 'c']
 ['1' '2' '3']
 ['t' '2' 'p']]

Shape:  (3, 3)

Shape:  2

Shape:  9

Shape:  <U21


### Dimensions

In [12]:
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )


# Checking the number of dimensions (axes)
print("No. of dimensions: ", arr.ndim)



No. of dimensions:  2


### Shape of array
        * array.shape


In [32]:
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Checking the shape of array
print("Shape of array: ", arr.shape)



Shape of array:  (2, 3)


In [40]:
array1 = np.array([[1,5,2],[3,2,1]])

print(array1)

print("Shape: ",array1.shape)

[[1 5 2]
 [3 2 1]]
Shape:  (2, 3)


### Size

In [14]:
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Checking the size (total number of elements) of array
print("Size of array: ", arr.size)



Size of array:  6


### Type of elements in array

In [15]:
# Creating array object
arr = np.array( [[ 1, 2, 3],
				[ 4, 2, 5]] )

# Checking the type of elements in array
print("Array stores elements of type: ", arr.dtype)


Array stores elements of type:  int64


## Creating Array

### Array from list

In [16]:
# Creating array from list with type float
a = np.array([[1, 2, 4], [5, 8, 7]], dtype = 'float')
print ("Array created using passed list:\n", a)



Array created using passed list:
 [[1. 2. 4.]
 [5. 8. 7.]]


### Array from tuple

In [49]:
# Creating array from tuple
b = np.array((1 , 3, 2))
print ("\nArray created using passed tuple:\n", b)



Array created using passed tuple:
 [1 3 2]


In [51]:
# Creating array from tuple
b1 = np.array([1 , 3, 2])
print ("\nArray created using passed tuple:\n", b1)



Array created using passed tuple:
 [1 3 2]


### Creating an array with all zeros
      * np.zeros((m, n))


In [18]:
# Creating a 3X4 array with all zeros
c = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", c)



An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
d = np.zeros((4,5))
print(d)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
# Create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array initialized with all 6s."
			"Array type is complex:\n", d)



An array initialized with all 6s.Array type is complex:
 [[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [58]:
d1 = np.full((4,3), 6, dtype = "complex")

print(d1)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [28]:
# Create an array with random values
e = np.random.random((2, 2))
print ("A random array:\n", e)


A random array:
 [[0.12933097 0.92078753]
 [0.91004653 0.64166649]]


In [30]:
# Create a sequence of integers
# from 0 to 30 with steps of 5
f = np.arange(0, 30, 5)
print ("A sequential array with steps of 5:\n", f)



A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [31]:
# Create a sequence of 10 values in range 0 to 5
g = np.linspace(0, 5, 10)
print ("A sequential array with 10 values between"
										"0 and 5:\n", g)


A sequential array with 10 values between0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [23]:
# Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4],
				[5, 2, 4, 2],
				[1, 2, 0, 1]])

newarr = arr.reshape(2, 2, 3)

print ("\nOriginal array:\n", arr)
print ("Reshaped array:\n", newarr)




Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [65]:
abc = np.array([[1,2,3],[5,6,4],[3,8,5]])
print(abc)

print(""*10)
reshapeabc = abc.reshape(3,1,3)   # (new array count, No. of rows in each array, no. of clms in each array)
print(reshapeabc)

print(""*10)
reabc = abc.reshape(3,3,1) #(3 array, 3 row in each array, 1 clm in each array)
print(reabc)

[[1 2 3]
 [5 6 4]
 [3 8 5]]

[[[1 2 3]]

 [[5 6 4]]

 [[3 8 5]]]

[[[1]
  [2]
  [3]]

 [[5]
  [6]
  [4]]

 [[3]
  [8]
  [5]]]


In [24]:
# Flatten array
arr = np.array([[1, 2, 3], [4, 5, 6]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)



Original array:
 [[1 2 3]
 [4 5 6]]
Fattened array:
 [1 2 3 4 5 6]
